/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sa;
import java.awt.Color;
import javax.swing.JOptionPane;
/**
 *
 * @author LnT
 */
public class TelaFinal extends javax.swing.JFrame {
    Eventos event = new Eventos();
    CarroController ccarro = new CarroController();
    public static Carro carro_select;
    /**
     * Creates new form TelaFinal
     */
    public TelaFinal() {
        initComponents();
        setLocationRelativeTo(null);
        Color minhaCor = new Color(240, 255, 240);
        getContentPane().setBackground(minhaCor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Voltar = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        cnh = new javax.swing.JTextField();
        telefone = new javax.swing.JTextField();
        idade = new javax.swing.JTextField();
        tipo_compra = new javax.swing.JLabel();
        qtd_dias = new javax.swing.JLabel();
        nome_label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tel_label = new javax.swing.JLabel();
        idade_label = new javax.swing.JLabel();
        tipo_de_compra_label = new javax.swing.JLabel();
        qtd_dias_label = new javax.swing.JLabel();
        confBtn = new javax.swing.JButton();
        aviso = new javax.swing.JLabel();
        aviso2 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Voltar.setBackground(new java.awt.Color(0, 0, 0));
        Voltar.setForeground(new java.awt.Color(255, 204, 153));
        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setText("Dados Cadastrais");
        titulo.setToolTipText("");

        nome.setBackground(new java.awt.Color(204, 255, 204));
        nome.setForeground(new java.awt.Color(0, 0, 0));
        nome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        cnh.setBackground(new java.awt.Color(204, 255, 204));
        cnh.setForeground(new java.awt.Color(0, 0, 0));
        cnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        cnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnhActionPerformed(evt);
            }
        });

        telefone.setBackground(new java.awt.Color(204, 255, 204));
        telefone.setForeground(new java.awt.Color(0, 0, 0));
        telefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneActionPerformed(evt);
            }
        });

        idade.setBackground(new java.awt.Color(204, 255, 204));
        idade.setForeground(new java.awt.Color(0, 0, 0));
        idade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        idade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idadeActionPerformed(evt);
            }
        });

        tipo_compra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tipo_compra.setText("jLabel1");

        qtd_dias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qtd_dias.setText("jLabel2");

        nome_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nome_label.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Categoria CNH:");

        tel_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tel_label.setText("Tel:");

        idade_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idade_label.setText("Idade:");

        tipo_de_compra_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tipo_de_compra_label.setText("Tipo de serviço:");

        qtd_dias_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qtd_dias_label.setText("Quantidade de dias:");

        confBtn.setBackground(new java.awt.Color(0, 0, 0));
        confBtn.setForeground(new java.awt.Color(255, 255, 102));
        confBtn.setText("FINALIZAR");
        confBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confBtnActionPerformed(evt);
            }
        });

        aviso.setForeground(new java.awt.Color(255, 0, 0));

        aviso2.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Voltar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(aviso2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(aviso, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome_label, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idade, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cnh, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tel_label, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idade_label, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(qtd_dias_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tipo_de_compra_label, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tipo_compra)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(qtd_dias, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(98, 98, 98)
                                            .addComponent(confBtn))))))))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Voltar))
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(nome_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tel_label))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aviso, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aviso2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idade_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipo_de_compra_label)
                    .addComponent(tipo_compra))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qtd_dias_label)
                            .addComponent(qtd_dias))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confBtn)
                        .addGap(24, 24, 24))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        // TODO add your handling code here:
        event.nextWindow(new Menu(), this);
        //        Menu box = new Menu();
        //        box.show();
        //        dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        
    }//GEN-LAST:event_nomeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        event.centerJFrame(this);
        qtd_dias.setText(String.valueOf(Cliente.getQtd_dias()));
        if(Cliente.getCompra() == 0){
            tipo_compra.setText("Aluguel");
        } else if (Cliente.getCompra() == 1){
            tipo_compra.setText("Compra");
            qtd_dias.setText("");
            qtd_dias_label.setText("");
        }
              
    }//GEN-LAST:event_formWindowOpened

    private void cnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnhActionPerformed

    private void confBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confBtnActionPerformed
        try{
            String inputCnh = cnh.getText().toUpperCase();
            int inputIdade = Integer.parseInt(idade.getText());
     
            aviso.setText("");
            aviso2.setText("");

            if(!("B".equals(inputCnh)|| "C".equals(inputCnh) || "D".equals(inputCnh) || "E".equals(inputCnh))){
                aviso.setText("Sua categoria deve ser acima de B \n");
                return;
            }

            if(inputIdade < 18){
                aviso2.setText("Você deve ter idade maior de 18");
                return;
            }
            String show =
                    "SEUS DADOS\n\nNome: " + nome.getText() +
                    "\nTelefone: " + telefone.getText();
            
                show = show+"\n\nDADOS DO VEÍCULO\n";
               show = show + "\nModelo: " + carro_select.getModelo(); 
               show = show + "\nMarca: " + carro_select.getMarca(); 
               show = show + "\nAno: " + carro_select.getAno(); 
               
               if (Cliente.getCompra() == 0){
                show = show + "\nValor Total de Diárias: R$" + String.valueOf(carro_select.getPrecoAluguel() * Cliente.getQtd_dias());
            } else if (Cliente.getCompra() == 1){
                show = show + "\nValor Total da Compra: R$" + String.valueOf(carro_select.getPrecoCompra());
            }
               
               show = show + "\n\nO nosso Atendente entrará em contato para finalizar seu Atendimento.\nA equipe Mão na Roda agradece pela preferência!";
                      
               System.out.println(carro_select.getPrecoCompra());
            JOptionPane.showMessageDialog(
                    null,
                    show,
                    "Dados Finais",
                    JOptionPane.INFORMATION_MESSAGE
            );
            
        } catch (NumberFormatException erro) {
            aviso.setText("Digite números válidos");
        }
        
        
    }//GEN-LAST:event_confBtnActionPerformed

    private void telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneActionPerformed

    private void idadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel aviso;
    private javax.swing.JLabel aviso2;
    private javax.swing.JTextField cnh;
    private javax.swing.JButton confBtn;
    private javax.swing.JTextField idade;
    private javax.swing.JLabel idade_label;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nome;
    private javax.swing.JLabel nome_label;
    private javax.swing.JLabel qtd_dias;
    private javax.swing.JLabel qtd_dias_label;
    private javax.swing.JLabel tel_label;
    private javax.swing.JTextField telefone;
    private javax.swing.JLabel tipo_compra;
    private javax.swing.JLabel tipo_de_compra_label;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
